### ISSUE TITLE
在go run过程中报错

### ISSUE THREAD

**Issue by Linvery** [PBK-B/gpt-zmide-server#11]
![image](https://user-images.githubusercontent.com/23356865/231073461-db6f1865-7988-4705-8ede-410185a0486a.png)

[root@VM-12-9-opencloudos gpt-zmide-server]# go run .
main.go:31:12: pattern dist/assets: no matching files found

**Comment by Linvery** [comment]
go version go1.18.9 linux/amd64

**Comment by PBK-B** [comment]
@Linvery 需要先执行 `npm install && npm run build` 编译前端资源
