### ISSUE TITLE
install时连接openai失败

### ISSUE THREAD

**Issue by Draculabo** [PBK-B/gpt-zmide-server#4]
我本地是能访问openai服务的
![image](https://user-images.githubusercontent.com/49336820/227841852-e2685591-a4b3-4f93-9f49-c84761b12c83.png)
但是我在http://127.0.0.1:8091/install的《配置 OpenAI Tab》栏时点击下一步提示连接失败，我是还有什么东西没有配置好吗？
![image](https://user-images.githubusercontent.com/49336820/227842328-55aa2661-0a75-4756-8eb8-3cb79e5059dd.png)
![image](https://user-images.githubusercontent.com/49336820/227842053-4d0bd100-03ff-47d6-8b4e-cc7db3a002d8.png)
![image](https://user-images.githubusercontent.com/49336820/227842142-ced4d435-6f56-4b39-b517-c625976f8f83.png)

**Comment by PBK-B** [comment]
@Draculabo http_proxy_host 不是这么配置的 🤔，这个得修改 
https://github.com/PBK-B/gpt-zmide-server/blob/master/helper/config.go#L176
https://github.com/PBK-B/gpt-zmide-server/blob/master/models/chat.go#L86

**Comment by Draculabo** [comment]
感谢，已更改。

**Comment by Draculabo** [comment]
感谢，已更改。

**Comment by PBK-B** [comment]
@Draculabo 使用最新版本，支持在 app.conf 设置 base_url 调整 OpenAI API 的地址了，例如
```
site_name: gpt-zmide-server
……
openai:
    secret_key: xxxxxxxxxxxxxxxxx
    ……
    base_url: https://api.openai.com
```

**Comment by Linvery** [comment]
> @Draculabo 使用最新版本，支持在 app.conf 设置 base_url 调整 OpenAI API 的地址了，例如
> 
> ```
> site_name: gpt-zmide-server
> ……
> openai:
>     secret_key: xxxxxxxxxxxxxxxxx
>     ……
>     base_url: https://api.openai.com
> ```
![image](https://user-images.githubusercontent.com/23356865/231990548-cb4e53e0-e595-4152-9c5d-20fcca2515b7.png)

建议在后台设置和install页面添加关于base_url的设置 @PBK-B
